site_name: Tananyagok
theme:
  name: material
  language: hu
  features:
    - content.code.copy
    - navigation.top
  palette:
    # Világos mód (alapértelmezett)
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Váltás sötét módra
    # Sötét mód
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Váltás világos módra
copyright: Czeglédi Dávid &copy; 2026. Minden jog fenntartva.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/czegledi-david
      name: GitHub repo
plugins:
  - awesome-pages
  - search
  - glightbox
  - mkdocs-pdf
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences
  - attr_list
